version: "3.9"

services:
  app:
    build: .
    container_name: ignews-next
    restart: always
    ports:
      - 3000:3000
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
